language: c

compiler: gcc

env:
- COMMIT_SHA=0940f7418e4653670d6ffe1217a5ef54a2e5c71c

install:
- wget https://developer.arm.com/-/media/Files/downloads/gnu-a/8.2-2019.01/gcc-arm-8.2-2019.01-x86_64-aarch64-linux-gnu.tar.xz
- tar xf gcc-arm-8.2-2019.01-x86_64-aarch64-linux-gnu.tar.xz
- export CROSS_COMPILE=$(pwd)/gcc-arm-8.2-2019.01-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-
- export ARCH=arm64

script:
- wget -qO- https://github.com/acuicultor/Radioactive_kernel_op6/archive/${COMMIT_SHA}.tar.gz | tar xz
- mv Radioactive_kernel_op6-${COMMIT_SHA} Radioactive_kernel_op6
- cd Radioactive_kernel_op6
- patch Makefile < ../Makefile.patch
- sed -i '4d' Makefile
- sed -i '4iEXTRAVERSION = -Radioactive-'${COMMIT_SHA:0:7} Makefile
- mkdir -p out
- make O=out mrproper
- make O=out radioactive_defconfig
- make O=out -j$(nproc --all)

deploy:
  provider: releases
  api_key:
    secure: E2uK0we/uY7n3opirUtUDHL2lFplCf5W2s3WTZOPhY0NraYwW6iCmvNzEGX9QqJcFjfuR5u0AapKFyUhCWVwWxNBgasIdCH5hT4rckeKErcnZPLxa6kbXixPs2nUSEJEEMza5ZJdvL4Y2L5UG9UoncxB59LWWE1Q92g2ZUfeZuHyQq5vInc5PVoEd02b84RDdbcDqBDiXUsce1TIdx+A6EwcdAXLv0ts5XgzTApXU3ZUywhM8Ie0RiwE4oFN8CnWXb+qdS4LV92EY9N4M07dKZElHIw1qY2z9DDBEPS9YFzEV+MJW+cMgJ4ZEeKPwg4DrZ5rcpAc47ikf54jQezWTSDgUU8Y3WsIHJPtvEdU71dVEavmnGlK4Kv+8GfFWf2rr5kYQVR2N2iJ50RPPEaFJJAgLFlRskC0xHJlPd5ubbA9rOHsnYUGZYH2LAfjGLVQ+2XQcqg4QZqYSEpzTpORFHJL/5RpjZ+5l3XTXW1JlbqFDnLa37yysrWklTzf4UAVTYY+Lo1J85rZXaj7l5c1pMix2xAPpGcve5IKpZKh76sLeePd9f2k5CK8IRzjg85O4MGkRnqfh92CPKWpaxjlL/+JAgV9Cne67GQ9B6kVHuFOtr/d8/8aGEXXK+LmP7OIGiyCTA40qMlqmVeQeuEmBFMXHrRE/mImeU79RSSaftw=
  file: "/home/travis/build/Hubedge/build_Radioactive_kernel_op6/Radioactive_kernel_op6/out/arch/arm64/boot/Image.gz-dtb"
  skip_cleanup: true
  on:
    tags: true
