--- Makefile	2019-03-02 16:25:35.278108200 +0800
+++ Makefile.new	2019-03-02 16:24:43.693183900 +0800
@@ -395,7 +395,7 @@
 		   -fno-strict-aliasing -fno-common -fshort-wchar \
 		   -Werror-implicit-function-declaration \
 		   -Wno-format-security -Wno-misleading-indentation -Wno-maybe-uninitialized -Wno-unused-function -Wno-address \
-		   -std=gnu89
+		   -std=gnu89 -mcpu=cortex-a75.cortex-a55+crypto+sve+dotprod
 KBUILD_CPPFLAGS := -D__KERNEL__
 KBUILD_AFLAGS_KERNEL :=
 KBUILD_CFLAGS_KERNEL :=
